### ISSUE TITLE
bug in timer1_hal.c

### ISSUE THREAD

**Issue by fsaberi** [Devilbinder/ATMEGA328P_C#1]
Hi
 in timer1_hal.c, you have this line in the sweep:
for(i = SEVRO_MIN; i <= SEVRO_MAX;i=+50){

the bug is that i is neverupdated. It should be:

i += 50

--Farhad

**Comment by Devilbinder** [comment]
fixed in https://github.com/Devilbinder/ATMEGA328P_C/pull/2
